### ISSUE TITLE
Module not found: Error: Can't resolve './lib-cov'

### ISSUE THREAD

**Issue by alcalyn** [Swatinem/wamp1#4]
I'm trying this npm module, so I:

- Installed it with `npm install wamp1`
- Included it in typescript with `import { Wamp } from 'wamp1';`
- And tried to open a ws connection with `var wamp = new Wamp('ws://0.0.0.0:8480');`

Then I get:

```
ERROR in ./node_modules/wamp1/index.js
Module not found: Error: Can't resolve './lib-cov' in '/.../node_modules/wamp1'
```

I can notice that there is a `node_modules/wamp1/lib/` folder, but no `lib-cov/` one.

If I try to skip this error by creating a fake `lib-cov/` folder with the same content as in `lib/`, I get the same error, but this time with `websocket-buffering`:

```
ERROR in ./node_modules/websocket-buffering/index.js
Module not found: Error: Can't resolve './lib-cov' in '/var/www/drop-portal/node_modules/websocket-buffering'
```

**Comment by Swatinem** [comment]
TBH, this is completely unmaintained. But patching it should be quite straight forward, just remove the conditional require, which was the "best practice" some 4 years for code coverage reporting. There are better solutions available today.

I’m open for a PR, but honestly you should pick a library that is better maintained.

**Comment by alcalyn** [comment]
I didn't found many js library for wamp v1 on npm. Even Autobahn 0.8 is not on npm. But it's ok, it's easier to include Autobahn as a file in my project.
